package presentacion.interfaz.ventana;

import java.sql.Date;
import java.util.Arrays;

import presentacion.Vista;
import presentacion.interfaz.dialogos.DialogoNombreYFecha;

/**
 *
 * @author Andres fecha creacion 27 ene 2026
 */
public class InterfazLogin extends javax.swing.JFrame {

	private static final java.util.logging.Logger logger = java.util.logging.Logger
			.getLogger(InterfazLogin.class.getName());

	private Vista vista;
	
	public InterfazLogin(Vista vista) {
		initComponents();
		this.vista=vista;
	}

	private void AceptarAccederActionPerformed(java.awt.event.ActionEvent evt) {
		String usuario= textUsuarioAcceder.getText();
		char[] contra = textContrasenaAcceder.getPassword();
		
		String contrasena = new String(contra);
		System.err.println(usuario.isEmpty());
		System.out.println(contrasena.isEmpty());
		if(usuario.isEmpty() || contrasena.isEmpty())
			System.out.println("Falta dialogo de completar campos");
		else {
			vista.acceder(usuario, contrasena);
		}

	}

	private void AceptarRegistrarActionPerformed(java.awt.event.ActionEvent evt) {
		boolean correcto = true;
		String usuario = textUsurioRegistrar.getText();

		if (usuario.isEmpty()) {
			correcto = false;
			System.out.println("sin usuario");

			

		}
		char[] contra = textContrasenaRegistrar.getPassword();
		char[] contraConfirmar = textContrasenaConfirmarRegistrar.getPassword();

		if (contra != null && contraConfirmar != null && Arrays.equals(contra, contraConfirmar)) {
			System.out.println("eee");

		} else {
			correcto = false;
			System.out.println("aaaa");
		}

		if (correcto) {
			DialogoNombreYFecha dNF = new DialogoNombreYFecha(this, true);
			dNF.setVisible(true);
			String nombre = dNF.getNombre();
			Date fechaNacimiento = dNF.getFechaNacimiento();
			String contrasena = new String(contra);
			vista.comprobarUsuario(usuario, contrasena, nombre, fechaNacimiento);
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		PanelFijo = new javax.swing.JPanel();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		PanelIntercambiar = new javax.swing.JPanel();
		SubPanelIntercambiar = new javax.swing.JPanel();
		PanelLogin = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		textUsuarioAcceder = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		textContrasenaAcceder = new javax.swing.JPasswordField();
		AceptarAcceder = new javax.swing.JButton();
		PanelRegistrar = new javax.swing.JPanel();
		jLabel3 = new javax.swing.JLabel();
		textUsurioRegistrar = new javax.swing.JTextField();
		textContrasenaRegistrar = new javax.swing.JPasswordField();
		textContrasenaConfirmarRegistrar = new javax.swing.JPasswordField();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		AceptarRegistrar = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		PanelFijo.setBackground(new java.awt.Color(255, 255, 255));

		jButton1.setText("Acceder");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton2.setText("Registrarse");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout PanelFijoLayout = new javax.swing.GroupLayout(PanelFijo);
		PanelFijo.setLayout(PanelFijoLayout);
		PanelFijoLayout
				.setHorizontalGroup(PanelFijoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(PanelFijoLayout.createSequentialGroup().addGap(48, 48, 48).addComponent(jButton1)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jButton2).addGap(80, 80, 80)));
		PanelFijoLayout.setVerticalGroup(PanelFijoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(PanelFijoLayout.createSequentialGroup().addGap(16, 16, 16)
						.addGroup(PanelFijoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jButton1).addComponent(jButton2))
						.addContainerGap(26, Short.MAX_VALUE)));

		PanelIntercambiar.setBackground(new java.awt.Color(204, 204, 204));

		SubPanelIntercambiar.setLayout(new java.awt.CardLayout());

		jLabel1.setText("Usuario");

		jLabel2.setText("Contraseña");

		AceptarAcceder.setText("Aceptar");
		AceptarAcceder.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				AceptarAccederActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout PanelLoginLayout = new javax.swing.GroupLayout(PanelLogin);
		PanelLogin.setLayout(PanelLoginLayout);
		PanelLoginLayout.setHorizontalGroup(PanelLoginLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(PanelLoginLayout.createSequentialGroup()
						.addGroup(PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(PanelLoginLayout.createSequentialGroup().addGap(18, 18, 18)
										.addGroup(PanelLoginLayout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel2))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(PanelLoginLayout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
												.addComponent(textUsuarioAcceder).addComponent(textContrasenaAcceder,
														javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)))
								.addGroup(PanelLoginLayout.createSequentialGroup().addGap(152, 152, 152)
										.addComponent(AceptarAcceder)))
						.addContainerGap(66, Short.MAX_VALUE)));
		PanelLoginLayout.setVerticalGroup(PanelLoginLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(PanelLoginLayout.createSequentialGroup().addGap(23, 23, 23)
						.addGroup(PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel1).addComponent(textUsuarioAcceder,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(52, 52, 52)
						.addGroup(PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel2).addComponent(textContrasenaAcceder,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
						.addComponent(AceptarAcceder).addGap(30, 30, 30)));

		SubPanelIntercambiar.add(PanelLogin, "card2");

		jLabel3.setText("Usuario");

		jLabel4.setText("Contraseña");

		jLabel5.setText("Confirmar contraseña");

		AceptarRegistrar.setText("Aceptar");
		AceptarRegistrar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				AceptarRegistrarActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout PanelRegistrarLayout = new javax.swing.GroupLayout(PanelRegistrar);
		PanelRegistrar.setLayout(PanelRegistrarLayout);
		PanelRegistrarLayout.setHorizontalGroup(PanelRegistrarLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(PanelRegistrarLayout.createSequentialGroup().addContainerGap()
						.addGroup(PanelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabel5).addComponent(jLabel4).addComponent(jLabel3))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGroup(PanelRegistrarLayout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(textContrasenaRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, 280,
										Short.MAX_VALUE)
								.addComponent(textUsurioRegistrar).addComponent(textContrasenaConfirmarRegistrar))
						.addContainerGap())
				.addGroup(PanelRegistrarLayout.createSequentialGroup().addGap(140, 140, 140)
						.addComponent(AceptarRegistrar).addContainerGap(204, Short.MAX_VALUE)));
		PanelRegistrarLayout.setVerticalGroup(PanelRegistrarLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(PanelRegistrarLayout.createSequentialGroup().addGap(30, 30, 30)
						.addGroup(PanelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel3).addComponent(textUsurioRegistrar,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(27, 27, 27)
						.addGroup(PanelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(textContrasenaRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel4))
						.addGap(28, 28, 28)
						.addGroup(PanelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(textContrasenaConfirmarRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel5))
						.addGap(18, 18, 18).addComponent(AceptarRegistrar).addContainerGap(23, Short.MAX_VALUE)));

		SubPanelIntercambiar.add(PanelRegistrar, "card3");

		javax.swing.GroupLayout PanelIntercambiarLayout = new javax.swing.GroupLayout(PanelIntercambiar);
		PanelIntercambiar.setLayout(PanelIntercambiarLayout);
		PanelIntercambiarLayout.setHorizontalGroup(PanelIntercambiarLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 416, Short.MAX_VALUE)
				.addGroup(PanelIntercambiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(SubPanelIntercambiar, javax.swing.GroupLayout.Alignment.TRAILING,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)));
		PanelIntercambiarLayout.setVerticalGroup(PanelIntercambiarLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 215, Short.MAX_VALUE)
				.addGroup(PanelIntercambiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(SubPanelIntercambiar, javax.swing.GroupLayout.Alignment.TRAILING,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup().addContainerGap()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addComponent(PanelIntercambiar, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(PanelFijo, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addComponent(PanelFijo, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18).addComponent(PanelIntercambiar, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addContainerGap()));

		pack();
	}// </editor-fold>

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		SubPanelIntercambiar.removeAll();
		SubPanelIntercambiar.add(PanelRegistrar);
		SubPanelIntercambiar.repaint();
		SubPanelIntercambiar.revalidate();

	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		SubPanelIntercambiar.removeAll();
		SubPanelIntercambiar.add(PanelLogin);
		SubPanelIntercambiar.repaint();
		SubPanelIntercambiar.revalidate();
	}

	// Variables declaration - do not modify
	private javax.swing.JButton AceptarAcceder;
	private javax.swing.JButton AceptarRegistrar;
	private javax.swing.JPanel PanelFijo;
	private javax.swing.JPanel PanelIntercambiar;
	private javax.swing.JPanel PanelLogin;
	private javax.swing.JPanel PanelRegistrar;
	private javax.swing.JPanel SubPanelIntercambiar;
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JPasswordField textContrasenaAcceder;
	private javax.swing.JPasswordField textContrasenaConfirmarRegistrar;
	private javax.swing.JPasswordField textContrasenaRegistrar;
	private javax.swing.JTextField textUsuarioAcceder;
	private javax.swing.JTextField textUsurioRegistrar;
	// End of variables declaration

}
